(* ::Package:: *)

(*<<maTHEMEatica`
SetOptions[EvaluationNotebook[], DefaultNewCellStyle->"Code"];
colors = <|
	"background"->RGBColor["#000000"],
	"fontcolor"->RGBColor["#eeeeee"],
	"primary"->RGBColor["#B87333"],
	"variable"->RGBColor["#55f7df"],
	"module"->RGBColor["#e638e9"],
	"block"->RGBColor["#FFFF00"],
	"error"->RGBColor["#FF0000"],
	"headhighlight"->RGBColor["#02584c"]
|>;
SetColors[colors]
CreateStyleSheet[]
ApplyStyleSheet[]*)


(* ::Section:: *)
(*Package Header*)


BeginPackage["FelipeBarbosa`SymDALI`DerivativeTools`"];

DerivativeRules::usage="DerivativeRules[{name, vars, n}, expr] returns a list of Rules where each rule is a possible derivative of expr with respecto to vars, from order 1 to n, 
and the second element is the corresponding pure Function";
CLibraryFunction::usage="returns the LibraryFunction generated by Compile";
SaveSymRules;
SaveNRules;
DerivativeRulesLoad;
$Block;


Begin["`Private`"]


(* ::Section:: *)
(*Definitions*)


Attributes[genErrorMessage] = HoldAll;

genErrorMessage[test_] := Module[
	{message},
	
	message = ToString[Unevaluated[test]];
	
	If[
		test,
		True,
		"The following Conditions were not satisfied: " <> message
	]
] 


DerivativeCombinations::usage="DerivativeCombinations[vars_, n_, zerothDerivative_]
vars_List: List of variables with respect to which you want derivatives;
n_Integer: max derivative order;
zerothDerivative_?BooleanQ: Whether to include the \"zero derivative\" in the list;
Output: List of all derivatives from order 1 (or zero) to n.
Example:

>>DerivativeCombinations[{x,y}, 2, True]
>>{{{}},{x},{y},{x,x},{x,y},{y,y}}";

DerivativeCombinations[vars_List, n_Integer, zerothDerivative_?BooleanQ]/;n>0 := Module[
	{result},
	
	result  = Table[
			(Sort/@Tuples[vars, i])//DeleteDuplicates,
			{i,n}
	]//Flatten[#,1]&;
	
	If[
		zerothDerivative,
		Prepend[result, {{}}],
		result
	
	]
]

(*I took this from Shiffrin's answer in: https://mathematica.stackexchange.com/questions/29321/what-are-the-best-practices-most-common-idiomatic-ways-to-report-errors-in-m *)

DerivativeCombinations[args___] := Throw[$Failed, failTag[DerivativeCombinations]]


Attributes[$Block] = {HoldAll};

$Block[{{heads___}, othervars___}, expression___] := Block[{heads, othervars}, expression]


DerivativesExpression::usage="DerivativesExpression[expr, derivatives, {kernels}, {keepDefs}]
expr_: expression to take derivatives;
derivatives_List: list of derivatives you want to apply in expr;
{kernels_Integer} || {}: number of kernels on which to parallelize the calculation of derivatives;
{keepDefs___Rule}: definitions of internal variables you want to keep, like S = \!\(\*SuperscriptBox[\(x\), \(2\)]\); A = y+x; and so on;
Output: List containing all derivatives of \"expr_\" as specified in \"derivatives_List\".
Example:

DerivativesExpression[g[x] h[\!\(\*SuperscriptBox[\(x\), \(2\)]\)], {{x}, {x,x}}, {}, {S-> \!\(\*SuperscriptBox[\(x\), \(2\)]\)}]
>>>{
	h[S] \!\(\*SuperscriptBox[\(g\), \(\[Prime]\),\nMultilineFunction->None]\)[x]+2 x g[x] \!\(\*SuperscriptBox[\(h\), \(\[Prime]\),\nMultilineFunction->None]\)[S],
	2 g[x] \!\(\*SuperscriptBox[\(h\), \(\[Prime]\),\nMultilineFunction->None]\)[S]+4 x \!\(\*SuperscriptBox[\(g\), \(\[Prime]\),\nMultilineFunction->None]\)[x] \!\(\*SuperscriptBox[\(h\), \(\[Prime]\),\nMultilineFunction->None]\)[S]+h[S] \!\(\*SuperscriptBox[\(g\), \(\[Prime]\[Prime]\),\nMultilineFunction->None]\)[x]+4 S g[x] \!\(\*SuperscriptBox[\(h\), \(\[Prime]\[Prime]\),\nMultilineFunction->None]\)[S]
}";

DerivativesExpression[expr_,  derivatives_List, {}, {keepDefs___Rule}] := Module[
	{result, rules},
	result = D[expr, Sequence@@#]&/@derivatives;
	(*Implement the definitions, if there are any:*)
	rules = Dispatch@(Reverse/@{keepDefs});
	result//.rules
]

DerivativesExpression[expr_, derivatives_List, {kernels_Integer}, {keepDefs___Rule}]/;Positive[kernels] := Module[
	{result, rules},
	LaunchKernels@@{kernels};
	result = ParallelMap[D[expr, Sequence@@#]&, derivatives, Method->"CoarsestGrained"];
	CloseKernels[];
	
	(*Implement the definitions, if there are any:*)
	rules = Dispatch@(Reverse/@{keepDefs});
	result//.rules
]

DerivativesExpression[x___] := Throw[$Failed, failTag[DerivativeExpression]]


Parser::usage="Parser[expr_]/;(Head@Unevaluated[expr]===$Block)
expr_: $Block[{{heads___}, otherVars___}, defs___]
Output: Same expression with $Block -> HoldComplete and {heads___} -> unique versions of the heads.
Example:
Parser[
	$Block[
		{{h1,h2}},
		h1[x_] = x+2;
		h2[x_] = x+3;
		h1[h2[x]]
	]
]
>>>HoldComplete[
	{{h11,h12}},
	h11[x_]=x+2;
	h12[x_]=x+3;
	h11[h12[x]]
]";

Attributes[Parser] = {HoldFirst};

Parser[expr_]/; (Head@Unevaluated[expr]===$Block) := Module[
	{iexpr, hs, uniquehs},
	(*Make the iexpr with HoldComplete*)
	iexpr = HoldComplete@@(Unevaluated@expr);
		
	(*Get Hold[h1,h2,h3,...]*)
	hs = (Hold@@@Extract[iexpr, {1,1}, Hold])//Flatten;
		
	(*Get: {HoldPattern[h1], HoldPattern[h2], ...}*)
	hs = List@@(HoldPattern/@hs);
		
	(*Make unique heads:*)
	uniquehs = Unique@("h"&/@Range[Length@hs]);
		
	(*change {h1, h2,...} in iexpr by {h1$nnn, h2$nnn,...}*)
	iexpr//.(Thread[Rule[hs, uniquehs]])
]

Parser[x___] := Throw[$Failed, failTag[Parser]]


iFunctionOccurrences::usage="iFunctionOccurrences[ExplicitDs, head]
ExplicitDs_List: List of explicit Derivative Functions;
head_Symbol: head appearing in \"ExplicitDs\"
Output: List of all occurrences of h and its derivatives in \"ExplicitDs\"
Example:

>>>Block[\[IndentingNewLine]	{list},
	list = {
		
		D[F[g[h[x]]], x], 
		
		D[F[g[h[x]]],{x,2}], 
		
		D[F[ g[h[x]], h[x], g[x] ], {x,3}], 
		D[F[h[x]], x, x]
	};
	
	iFunctionOccurrences[list, g]\[IndentingNewLine]]
>>> {g[h[x]],g[x],g'[h[x]],g''[h[x]],g'''[x],g'''[h[x]],g''[x],g'[x]}";

iFunctionOccurrences[ExplicitDs_List, head_Symbol] := Module[
	{hs, Ds, args, n},
	
	hs = Cases[ExplicitDs, head[args__], Infinity]//DeleteDuplicates;
	Ds = Cases[ExplicitDs, Derivative[n__][head][args__], Infinity]//DeleteDuplicates;
	
	Join[hs,Ds]
]

iFunctionOccurrences[x___] := Throw[$Failed, failTag[iFunctionOccurrences]]


MaxDepth::usage="MaxDepth[expr, h]
expr_: symbolic expression
h_Symbol: head for which you want the depths
Output: Finds the maximum depth of occurrences of \"h\" in \"expr\". Depth is calculated as the Lenght of all Position 
vectors indicating the position of \"h\" in \"expr\".
Obs.: For expressions involving derivatives is necessary to apply
	Derivative[n__][s_][args__]/;{args}[[1,0]] =!= List :> Derivative[n__][s_][{args__}]
to \"expr\" before MaxDepth, so that arguments of the function are in a higher Depth than \"s\" itself

Example:
>>>Block[
	{list},
	list = {D[F[g[h[x]]], x], D[F[g[h[x]]], {x,2}]}//.Derivative[n__][s_][args__]/;{args}[[1,0]] =!= List :> Derivative[n][s][{args}];

	{MaxDepth[list, F], MaxDepth[list, g], MaxDepth[list, h]}
]
>>>{
	{3,4},
	{4,5},
	{5,6}

}";

Attributes[MaxDepth] = Listable;

MaxDepth[expr_, h_] := Module[
	{positions, depths},
	
	positions = Position[expr, h, Infinity];
	
	depths = Length/@positions;
	
	If[
		Max@depths == - \[Infinity],
		0,
		Max@depths
	]
]

MaxDepth[x___] := Throw[$Failed, failTag[MaxDepth]]


FunctionOccurrences::usage="FunctionOccurrences[ExplicitDs, heads]
ExplicitDs_List: list of symbolic derivatives involving implicit functions;
heads_List: list of heads appearing in \"ExplicitDs\"
Output: List of all occurrences of the functions specified in \"heads\" including their derivatives, from the innermost
to the outtermost function, and a list of the corresponding heads in the order they appear.

Example:
>>>Block[\[IndentingNewLine]	{list},
	list = {
		D[F[g[h[x]]], x], 
		D[F[g[h[x]]],{x,2}]
	};
	
	FunctionOccurrences[list, {g, h, F}]\[IndentingNewLine]]
>>>{
	{
		{h[x],\!\(\*SuperscriptBox[\(h\), \(\[Prime]\),\nMultilineFunction->None]\)[x],\!\(\*SuperscriptBox[\(h\), \(\[Prime]\[Prime]\),\nMultilineFunction->None]\)[x]},
		{g[h[x]],\!\(\*SuperscriptBox[\(g\), \(\[Prime]\),\nMultilineFunction->None]\)[h[x]],\!\(\*SuperscriptBox[\(g\), \(\[Prime]\[Prime]\),\nMultilineFunction->None]\)[h[x]]},
		{\!\(\*SuperscriptBox[\(F\), \(\[Prime]\),\nMultilineFunction->None]\)[g[h[x]]],\!\(\*SuperscriptBox[\(F\), \(\[Prime]\[Prime]\),\nMultilineFunction->None]\)[g[h[x]]]}
	},
	{h,g,F}
}";

FunctionOccurrences[ExplicitDs_List, uniqueheads_List] := Module[
	{iExplicitDs, HeadDepth, iuniqueheads, result},
	
	(*Make an internal List of D's that puts f and g in different levels (as calculated by MaxDepth) in f'[g[x]]*)
	iExplicitDs = ExplicitDs//.Derivative[n__][s_][args__]/;{args}[[1,0]] =!= List :> Derivative[n][s][{args}];
	
	(*Calculate the Depth of everyone:*)
	(HeadDepth[#] = Max[MaxDepth[iExplicitDs, #]])&/@uniqueheads;
	
	(*Organize the heads from the innermost to the outermost:*)
	iuniqueheads = ReverseSortBy[uniqueheads, HeadDepth];
		
	result = iFunctionOccurrences[ExplicitDs, #]&/@iuniqueheads;
	
	{result, iuniqueheads}
]

FunctionOccurrences[x___] := Throw[$Failed, failTag[FunctionOccurrences]]


Attributes[iClear] = {HoldAll};
iClear[x__] := (Clear[x]; Nothing)


UniqueVars::usage="UniqueVars[expr, functions, heads, {defs}]
expr_HoldComplete: parsed $Block expression, with respect to which one is taking derivatives;
functions_List: list of functions and function derivatives that appear in the derivatives of \"expr\";
heads_List: list of heads appearing in \"functions\" in the order that they appear;
{defs___Rule}: variable definitions that one wants to keep.
Output: Association containg 2 lists of rules. 
-> List1: $xi variables and their explicit definition. 
-> List2: $xi variables and their correspondence to implicit functions appearing in \"functions\".
Example:

Module[
	{expr, functions, heads},
	expr = HoldComplete[
		{{h1,h2,h3}},
		h1[x_] = 3 \!\(\*SuperscriptBox[\(x\), \(2\)]\); h2[x_] = Sin[x]; h3[x_] = Cosh[x];
		h1[h2[x]] h3[x]
	];

	{functions, heads} = FunctionOccurrences[{D[h1[h2[x]] h3[x], x], D[h1[h2[x]] h3[x],x,x]}, {h1,h2,h3}];

	UniqueVars[expr, functions, heads, {}]
]
>>>\[LeftAssociation]
	\"x$DEF\"\[Rule]{$x1\[Rule]Sin[x],$x2\[Rule]Cos[x],$x3\[Rule]-Sin[x],$x4\[Rule]Cosh[x],$x5\[Rule]Sinh[x],$x6\[Rule]Cosh[x],$x7\[Rule]3 \!\(\*SuperscriptBox[\($x1\), \(2\)]\),$x8\[Rule]6 $x1,$x9\[Rule]6},
	\"x$Correspondence\"\[Rule]{\!\(\*SuperscriptBox[\(h1\), \(\[Prime]\[Prime]\),\nMultilineFunction->None]\)[h2[x]]\[Rule]$x9,\!\(\*SuperscriptBox[\(h1\), \(\[Prime]\),\nMultilineFunction->None]\)[h2[x]]\[Rule]$x8,h1[h2[x]]\[Rule]$x7,\!\(\*SuperscriptBox[\(h3\), \(\[Prime]\[Prime]\),\nMultilineFunction->None]\)[x]\[Rule]$x6,\!\(\*SuperscriptBox[\(h3\), \(\[Prime]\),\nMultilineFunction->None]\)[x]\[Rule]$x5,h3[x]\[Rule]$x4,\!\(\*SuperscriptBox[\(h2\), \(\[Prime]\[Prime]\),\nMultilineFunction->None]\)[x]\[Rule]$x3,\!\(\*SuperscriptBox[\(h2\), \(\[Prime]\),\nMultilineFunction->None]\)[x]\[Rule]$x2,h2[x]\[Rule]$x1}
\[RightAssociation]";

UniqueVars[expr_HoldComplete, functions_List, heads_List, {defs___Rule}] := Module[
	{ifunctions, idefs, $iiexpr = expr, list1, vars, list2},
	
	(*Make the function list to insert in the last term of expr*)
	ifunctions = Riffle[functions, iclear/@heads]//Flatten;
	(*List of all variables whose defs you want to keep:*)
	idefs = {defs}[[All,1]];
	(*Clear them before evaluation:*)
	$iiexpr[[-1,-1]] = Sequence[iclear@@idefs, ifunctions]; 
	
	(*Calculate the explicit definitions*)
	list1 = $Block@@($iiexpr//.iclear->iClear);
	
	(*Make the vars x$nnn*)
	vars = Symbol["$x" <> ToString[#]]&/@Range[Length@Flatten[functions]];
	
	(*make x$nnn -> explicit def*)
	list1 = Thread@Rule[vars, list1];
	
	(*Now make the list implicitdef -> x$nnn*)
	list2 = Thread@Rule[Flatten[functions], vars];
	
	(*Now, reverse the order, so that expressions with big depth appear first:*)
	list2 = Reverse[list2]; 
	
	(*eliminate things like Cos[h[x]] from explicit defs, assuming the implicit def is g[h[x]] and g[x_] = Cos[x]*)
	list1 = list1//.list2;
	
	<|"x$DEF" -> list1, "x$Correspondence" -> list2|>
]

UniqueVars[x___] := Throw[$Failed, failTag[UniqueVars]]


AbreviatedExpressions::usage="AbreviatedExpressions[expr, dexpressions, {defs}]
expr_HoldComplete: parsed $Block expression;
dexpressions_List: list of all implicit derivatives of \"expr\";
defs___Rule: variables you want to keep the definitions.
Output: list of 2 lists
-> list1: the derivative expressions in \"dexpressions\" with implicit functions replaced by $xi variables;
-> list2: list of rules that define the $xi variables explicitly.

Example:
>>>Module[
	{expr, dexpressions},
	expr = HoldComplete[
		{{h1,h2,h3}},
		h1[x_] = 3 \!\(\*SuperscriptBox[\(x\), \(2\)]\); h2[x_] = Sin[x]; h3[x_] = Cosh[x];
		h1[h2[x]] h3[x]
	];

	dexpressions = {h1[h2[x]] h3[x], D[h1[h2[x]] h3[x], x], D[h1[h2[x]] h3[x],x,x]};

	AbreviatedExpressions[expr, dexpressions, {}]
]
>>>{
	{$x4 $x7,$x5 $x7+$x2 $x4 $x8,$x6 $x7+$x3 $x4 $x8+2 $x2 $x5 $x8+\!\(\*SuperscriptBox[\($x2\), \(2\)]\) $x4 $x9},
	
	{$x1\[Rule]Sin[x],$x2\[Rule]Cos[x],$x3\[Rule]-Sin[x],$x4\[Rule]Cosh[x],$x5\[Rule]Sinh[x],$x6\[Rule]Cosh[x],$x7\[Rule]3 \!\(\*SuperscriptBox[\($x1\), \(2\)]\),$x8\[Rule]6 $x1,$x9\[Rule]6}
}";

AbreviatedExpressions[expr_HoldComplete, dexpressions_List, {defs___Rule}] := Module[
	{uniquehs = expr[[1,1]], functions, heads, association, idexpressions},
	
	(*all functions and function derivatives, and an association to indicate how many terms each head has*)
	{functions, heads} = FunctionOccurrences[Flatten[dexpressions], uniquehs];
	
	(*Make the explicit defs of Unique variables and their correspondence to implicit functions*)
	association = UniqueVars[expr, functions, heads, {defs}];
	idexpressions = dexpressions//.association["x$Correspondence"];
	
	
	(*Return the derivative expressions with unique vars and their correspondence to explicit functions*)
	{
		idexpressions,
		association["x$DEF"]
	}
]

AbreviatedExpressions[x___] := Throw[$Failed, failTag[AbreviatedExpressions]]


(*
	DExpression: derivative expression with depending on the xn's as defined in AbreviatedExpressions.
	For instance $x1 +$x2 $x3 x
	{symbols__}: all the $xn that appear in DExpression
	pool: Association with the explicit definition of the $xn's, for instance <|$x1 -> x^2, $x2-> Sin[x], $x3 -> y,... |>
	
	Output: Block function wrapped in HoldForm to calculate the derivative. For the defs above it would be:
		HoldForm@Block[
			{$x1,$x2,$x3},
			$x1 = x^2; 
			$x2 = Sin[x];
			$x3 = y;
			$x1 + $x2 $x3 x
	]

*)

DFunction[x_?NumberQ, {} , pool_Association, {defs___Rule}] := x

DFunction[DExpression_, {symbols__Symbol}, pool_Association, {defs___Rule}] := Module[
	{setdefs, compound, vars, expr, setdefsivars},
	
	(*make a sequence of defs $x1 = x^2 and so on, and definitions for the internal variables like a = x-y, ...*)
	setdefs = HoldComplete@@(Thread@set[{symbols},  pool/@{symbols}]);
	setdefsivars = HoldComplete@@(set@@@{defs});
	setdefs = Join[setdefsivars, setdefs];
	setdefs = Set@@@setdefs;
	
	(*make a compound expression for Block:*)
	compound = HoldComplete@@{Join[setdefs, HoldComplete[DExpression]]};
	compound = CompoundExpression@@@compound;
	
	(*declare the variables $x and internal variables from keep defs:*)
	vars = With[
		{ivars = {symbols}, iivars = {defs}[[All,1]]},
		HoldComplete[x]/. x-> Join[ivars, iivars]
	];
	
	(*make the expression:*)
	expr = Join[vars, compound];
	Block@@@(HoldForm[Evaluate@expr])
]

DFunction[x___] := Throw[$Failed, failTag[DFunction]]


iDependencySearch::usage="iDependencySearch[$xiList, $xiDefs]
$xiList_List: list of $xi vars;
$xiDefs_List: list of rules containig the defs of $xi;
Output: set of vars $xj on which the $xi in \"$xiList\" depend upon.

Example:
>>>Block[
	{$xiList, $xiDefs},

	$xiList = {$x2, $x5, $x6};
	
	$xiDefs = {
		$x1 -> Sin[x],
		$x2 -> Cos[x],
		$x3 -> Exp[$x1],
		$x4 -> 1 + Cos[x] \!\(\*SuperscriptBox[\($x3\), \(2\)]\),
		$x5 -> 1 - Sin[$x1] $x2,
		$x6 -> 1+ Exp[x] Cosh[a] Sin[2+ $x4]
	};
	iDependencySearch[$xiList, $xiDefs]
]
>>>{$x2,$x1,$x4}
";

iDependencySearch[primaryList_, $xiDefs_List] := Module[
	{ivars = $xiDefs[[All,1]], result},
	
	Cases[primaryList/.$xiDefs, Alternatives@@ivars, Infinity]//DeleteDuplicates
]

iDependencySearch[x___] := Throw[$Failed, failTag[iDependencySearch]]


DependencySearch::usage="DependencySearch[expr, $xiDefs]
expr: derivative expression with implicit functions replaced by $xi;
$xiDefs_List: list of rules giving explicit definitions of the $xi variables.
Output: all symbols $xi you need to define so that you  can calculate the expression \"expr\".

Example:
>>>Block[
	{expr, $xiDefs},

	expr = Sin[$x6] Exp[I $x2] + Cos[$x3];
	
	$xiDefs = {
		$x1 -> Sin[x],
		$x2 -> Cos[x],
		$x3 -> Exp[$x1],
		$x4 -> 1 + Cos[x] \!\(\*SuperscriptBox[\($x3\), \(2\)]\),
		$x5 -> 1 - Sin[$x1] $x2,
		$x6 -> 1+ Exp[x] Cosh[a] Sin[2+ $x4]
	};

	DependencySearch[expr, $xiDefs]
]
>>> {$x1,$x2,$x3,$x4,$x6}
";

DependencySearch[expr_, $xiDefs_List] := Module[
	{ivars = $xiDefs[[All,1]], firstList, result},
	
	firstList = Cases[expr, Alternatives@@ivars, Infinity]//DeleteDuplicates;
	
	result = FixedPointList[
		iDependencySearch[#, $xiDefs]&, 
		firstList
	];
	
	(Flatten[result]//DeleteDuplicates)//Sort
]

DependencySearch[x___] := Throw[$Failed, failTag[DependencySearch]]


AuxiliarFunctions::usage="AuxiliarFunctions[expr, derivativeVars, {parallel}, {defs}]
expr_: Function definition with respect to which you are going to take derivatives;
derivativesVars_List: list of derivatives you want to take;
parallel___Integer: number of kernels to launch to calculate the derivatives;
defs___Rule: variable definitions you want to keep;
Output: list of function derivatives";

Attributes[AuxiliarFunctions] = HoldFirst;

AuxiliarFunctions[expr_, derivativesVars_List, {parallel___Integer}, {defs___Rule}]/;(
	(Head@Unevaluated[expr]) =!= $Block
) := Module[
	{derivativesList},
	
	If[
		{parallel} === {},
		derivativesList = D[expr, Sequence@@#]&/@derivativesVars;,
		LaunchKernels@@{parallel};
		derivativesList = ParallelMap[D[expr, Sequence@@#]&, derivativesVars];
		CloseKernels[];
	];
	
	derivativesList
]

AuxiliarFunctions[expr_, derivativeVars_List, {parallel___Integer}, {defs___Rule}]/;(Head@Unevaluated[expr] == $Block) := Module[
	{iexpr,explicit, derivatives, dictionary, symbols, functions, numberPos},
		
		(*Get the parsed expression:*)
		iexpr = Parser[expr];
		
		(*Explicit expression:*)
		explicit = Module[
			{last = iexpr[[-1,-1]], iiexpr = iexpr, uniquehs = iexpr[[1,1]]},
			
			iiexpr[[-1,-1]] = Sequence[clear@@uniquehs, last];
			
			$Block@@(iiexpr//.clear->Clear)
		];
		
		(*Get all derivatives in terms of implicit functions:*)
		derivatives =  EchoTiming[
			DerivativesExpression[explicit, derivativeVars, {parallel}, {defs}], 
			"symbolic Derivatives:"
		];
		
		(*all function derivatives with f'[x] -> $xn and a dictionary for $xn -> explicit expression:*)
		{derivatives, dictionary} = EchoTiming[AbreviatedExpressions[iexpr, derivatives, {defs}], "sym derivatives -> $x and explicit derivatives: "];
		
		
		(*Get all symbols in each expression:*)
		symbols = DependencySearch[#, dictionary]&/@derivatives;
		
		(*make the functions:*)
		functions = EchoTiming[
			MapThread[
				DFunction[#1, #2, Association@dictionary, {defs}]&,
				{derivatives, symbols}
			], 
			"Make Block functions: "
		];
		
		(*Remove the unique heads previously generated*)
		Remove@@(iexpr[[1,1]]);
		Clear[iexpr];
		
		functions
]

AuxiliarFunctions[args___] := Throw[$Failed, failTag[AuxiliarFunctions]]


(*Block[
	{$xiList, $xiDefs},

	$xiList = {$x2, $x5, $x6};
	
	$xiDefs = {
		$x1 -> Sin[x],
		$x2 -> Cos[x],
		$x3 -> Exp[$x1],
		$x4 -> 1 + Cos[x] $x3^2,
		$x5 -> 1 - Sin[$x1] $x2,
		$x6 -> 1+ Exp[x] Cosh[a] Sin[2+ $x4]
	};

	iDependencySearch[$xiList, $xiDefs]
]*)


(*
	name: symbol without definition to be used as function name
	vars: variables of the function, for instance {x}
	derivativeVars: list of all required derivatives, for instance {{}, {x}, ...}
	functions: corresponding list of all functions obtained by taking the derivatives, for instance {x^2, 2x, ...}
	
	Output: List of rules of the type {
		name[x_] -> x^2,
		$D[{1}, name][x_] -> 2 x
		...
	}
	

*)

iDerivativeRules[name_Symbol, vars_List, derivativeVars_List, functions_List, zeroD_?BooleanQ] := Module[
	
	{derivativeHeadList, RulesList, patternVars, patternDerivativeVars, rule, nonzeroCases, numberCases, trivialRules},
	
	patternVars = Pattern[#, Blank[]]&/@vars;
	
	patternDerivativeVars = If[
		zeroD,
		Map[
			Pattern[#, Blank[]]&,
			Drop[derivativeVars,1],
			{2}
		],
		Map[
			Pattern[#, Blank[]]&,
			derivativeVars,
			{2}
		]
	];
	
	(*Include 0 derivative head if necessary*)
	derivativeHeadList = If[
		zeroD,
		Prepend[D[name@@patternVars, Sequence@@#]&/@patternDerivativeVars,  name@@patternVars],
		D[name@@patternVars, Sequence@@#]&/@patternDerivativeVars
	];
	
	derivativeHeadList = Replace[
		derivativeHeadList,
		Derivative[x__][y_Symbol][k__] -> $D[{x}, y][k],
		{1}
	];
	
	
	(*Now, finally construct the list of Rules*)
	RulesList = MapThread[
		(#1  -> #2)&,
		{derivativeHeadList, functions}
	];
	
	(*Reorganize such that the output is {{trivialRules}, {rules}}, trivialRules: FunctionDerivative ->NUMBER*)
	numberCases = Position[RulesList[[All, 2]], x_/;NumberQ@x, {1}];
	
	trivialRules = Extract[RulesList, numberCases];
	
	{
	trivialRules, 
	Delete[RulesList, numberCases]
	}
]

iDerivativeRules[args___] := Throw[$Failed, failTag[iDerivativeRules]]


DerivativeRules::fail="The function failed. The failure occured in function `1`";


Attributes[DerivativeRules] = HoldRest;

Options[DerivativeRules] = {"IncludeZeroDerivative" -> True, Assumptions -> $Assumptions, TimeConstraint->300, 
	"Parallel" -> {}, "KeepDefs" -> {}};

(*HOW CAN I CONSTRAIN THIS OPTION TO BE EITHER TRUE OR FALSE?*)
DerivativeRules[{name_, vars_, n_Integer}, expr_, OptionsPattern[]]/;(
	genErrorMessage@(
		Comap[{OwnValues, UpValues, SubValues, FormatValues, NValues, DownValues}, name] === ConstantArray[{}, 6]
	) &&
	genErrorMessage@(Head/@{name, vars, n} === {Symbol, List, Integer}) &&
	
	genErrorMessage@(Head/@vars === ConstantArray[Symbol, Length@vars] && n>0) &&
	
	genErrorMessage@(Comap[{OwnValues, DownValues, SubValues, UpValues}, name] === {{},{},{},{}})
	
) := Module[

	{listOfDerivatives, listOfFunctions, listOfRules, zeroCases, trivialRules},
	
	Catch[
		listOfDerivatives = DerivativeCombinations[vars, n, OptionValue[DerivativeRules, "IncludeZeroDerivative"]];
		listOfFunctions = AuxiliarFunctions[
			expr, 
			listOfDerivatives,
			OptionValue[DerivativeRules, "Parallel"],
			OptionValue[DerivativeRules, "KeepDefs"]
		];
		
		listOfRules = iDerivativeRules[name, vars, listOfDerivatives, listOfFunctions, OptionValue[DerivativeRules, "IncludeZeroDerivative"] ];
		listOfRules,
		_failTag,
		(Message[DerivativeRules::fail, Style[First@#2, Red]]; #1) &
	]
]


DerivativeRules[{name_, vars_, derivatives_List}, expr_, OptionsPattern[]]/;(
	genErrorMessage@(Comap[{OwnValues, DownValues, SubValues, UpValues}, name] === {{},{},{},{}})
) := Module[

	{listOfDerivatives, listOfFunctions, listOfRules, zeroCases, trivialRules},
	
	Catch[
		listOfDerivatives = derivatives;
		listOfFunctions = AuxiliarFunctions[
			expr, 
			listOfDerivatives,
			OptionValue[DerivativeRules, "Parallel"],
			OptionValue[DerivativeRules, "KeepDefs"]
		];
		
		listOfRules = iDerivativeRules[name, vars, listOfDerivatives, listOfFunctions, OptionValue[DerivativeRules, "IncludeZeroDerivative"] ];
		listOfRules,
		_failTag,
		(Message[DerivativeRules::fail, Style[First@#2, Red]]; #1) &
	]
]


Options[CLibraryFunction] = {
	CompilationOptions-> Automatic,
	Parallelization -> True,
	RuntimeAttributes -> {Listable},
	RuntimeOptions -> {
		"CatchMachineOverflow" -> False, 
		"CatchMachineIntegerOverflow" -> False, 
		"EvaluateSymbolically" -> False, 
		"RuntimeErrorHandler" -> None,
		"WarningMessages" -> True
	}
};

Attributes[CLibraryFunction] = {HoldRest};


CLibraryFunction[vars_List, expr_, OptionsPattern[]] := Module[
	{optsValues, opts, iexpr = Hold[expr]},
	
	optsValues = OptionValue[CLibraryFunction, #]&/@(Options[CLibraryFunction][[All,1]]);
	
	opts = Hold@@MapThread[
		Rule[#1,#2]&,
		{Options[CLibraryFunction][[All,1]], optsValues}
	];
	
	AppendTo[opts, CompilationTarget->"C"];
	
	(Compile@@Join[Hold[vars],iexpr, opts])[[-1]]
]


(*Tests if the file structure is:
	TheoryName:
		SymRules
		NRules
		Defs.wdx (may or may not exist)
*)

ParentDirectoryTest[directory_] := Module[
	{DirecName, PDirecName, isPDirecNameOk, PDirecContent, isPDirecContentOk, MacOSDefaultFile = ".DS_Store"},
	
	(*Take the Directory, ParentDirectory names*)
	DirecName =  FileNameTake[directory, -1];
	PDirecName = FileNameTake[ParentDirectory[directory], -1];
	
	
	(*test valid PDirecNames:*)
	isPDirecNameOk = StringCases[PDirecName, {"SymRules", "NRules", "Defs"}] === {};
	
	(*Now, test valid content in the PDirec*)
	PDirecContent = FileNameTake[#,-1]&/@FileNames[All, ParentDirectory[directory]];
	
	isPDirecContentOk = (
		Sort[PDirecContent] === {MacOSDefaultFile, "NRules", "SymRules"} ||
		Sort[PDirecContent] === {MacOSDefaultFile, "Defs.wdx", "NRules", "SymRules"}
	  );
	
	And[isPDirecContentOk, isPDirecNameOk]
]


(*Test for contents in SymRules and NRules:
	SymRules:
		.wdx files or empty
	NRules:
		empty
*)

DirectoryFilesTest[directory_] := Module[
	{
	PDirec, PDirecContent, isSymFilesOk, isNFilesOk, MacOSDefaultFile = ".DS_Store"
	},
	
	(*Take the Directory, ParentDirectory, prefix and theoryName *)
	PDirec = ParentDirectory[directory];
	
	
	(*See if the file contents are correct*)
	isSymFilesOk = StringMatchQ[#, {"*.wdx", ".DS_Store"}]&@FileNames[
		All,
		FileNameJoin[PDirec, "SymRules"] 
	]; (*This outputs either a list of true and False, or an empty list*)
		
	(*only True if the list is empty or full with Trues*)	
	isSymFilesOk = And@@isSymFilesOk;
	
	
	(*NFiles has to be empty, bcs I don't know how to change the name of a C function
	inside the file and mathematica uses the same names (CompiledFunction0, CompiledFunction1,...) in different
	kernelSessions, making it impossible to add files to the directory through different kernelSessions.*)
	isNFilesOk = FileNames[
		All, FileNameJoin[PDirec, "NRules"]
		] === {};
	
	
	 And[isSymFilesOk, isNFilesOk]
]	


FullDirectoryTest::fail = "You can only save files in the following directory structure:";


FullDirectoryTest[directory_] := Module[
	{result}, 
	
	result = ParentDirectoryTest[directory] && DirectoryFilesTest[directory];
	
	If[TrueQ@result, True, Throw[Message[FullDirectoryTest::fail]; directoryTree]]
	]


directoryTree = Tree[
	"TheoryName (any name but SymRules, NRules \[And] Defs)", 
	
		{
			Tree["SymRules", {"only .wdx files in this directory"}],
			Tree["NRules",  {"no files in this directory"}], 
			"Optional: Defs.wdx file here"
		
		}
	,
	Background->White
];


iSaveSymRules[{rule_, fileName_String}, directory_] := Export[
	FileNameJoin[directory, FileBaseName[fileName] <> ".wdx"], 
	rule
	];


iSaveNRules[rules_, directory_] := Module[

	{TranslationTable, fileNames, argsforCopyFile},
	
	TranslationTable = Replace[rules, LibraryFunction -> List, {2}, Heads->True];
	
	fileNames = FileNameTake[#, -1]&/@rules[[All, 2, 1]];
	
	argsforCopyFile = Riffle[
		rules[[All, 2, 1]], 
		FileNameJoin[directory, #]&/@fileNames
	]//Partition[#, 2]&;
	
	CopyFile@@@argsforCopyFile;
	
	(*Change the names in TranslationTable, making it easier to import LibraryFunctions:*)
	 Replace[TranslationTable,  Rule@@@argsforCopyFile, {3}]
]


SaveSymRules[{rules_Association, fileName_String}, directory_?DirectoryQ] := Module[
	{},
	
	Catch[
		FullDirectoryTest[directory];
		iSaveSymRules[{rules, fileName}, directory]
	];
]


SaveNRules[rules_Association, directory_?DirectoryQ] := Module[
	{ruleList},
	Catch[
		FullDirectoryTest[directory];
		
		
		ruleList = KeyValueMap[
			Rule[#1, iSaveNRules[#2, directory]]&,
			rules
		];
		
		Export[directory <> "/RosettaStone.wdx", Association@ruleList];
	];
]


ExtractLibraryFunction[x_]/; Head@x === CompiledFunction := x[[-1]]
ExtractLibraryFunction[x_] := x

MakeCompiledFunction[x_LibraryFunction,  expression_, WVM_] := Module[
	{vars =  x[[3, All, 1;;2]], compiledfunction, iexpression = expression, Blankvars},
	
	(*eliminate patterns from expression and convert it to string:*)
	iexpression = ToString[iexpression/. dummy_Pattern :> dummy[[1]]];
	
	(*Put the list of variables into the standard form for CompiledFunction:*)
	Blankvars = MapAt[Blank, vars, {All, 1}];
	
	compiledfunction = { (*These are the settings for the DefaultOptions of CLibraryFunction*)
		{11, $VersionNumber, 4760},
		Blankvars,
		Sequence@@WVM, (*WVM for the correct number of variables. Apparently it has to match the declared number*)
		Function[{}, Evaluate@iexpression, Listable],
		None,
		x
	};
	
	CompiledFunction@@compiledfunction
]


outType[Real] := 1.
outType[Complex] := I


makeWVM[vars_, OutputType_] := Module[
	{list},
	list  = List@@Compile[Evaluate@vars, Evaluate[ 1. + outType[OutputType] ], CompilationTarget->"WVM"
	];
	list[[3;;6]]
]


(*
vars: variables in  the lhs of the rules in NRules
LFvars: Library function vars: LibraryFunction[...][[3]]

Example:
>>> Block[{l1, l2}, 
	l1 = {{Real,0,"Constant"},{Real,0,"Constant"},{Real,0,"Constant"},{Real,0,"Constant"},{Real,0,"Constant"},{Real,0,"Constant"},{Real,1,"Constant"},{Real,2,"Constant"}};
	l2 = {x,y,z,w,k,t, u,v};
	
	MakeVars[l2,l1]
]
>>>{{x,_Real},{y,_Real},{z,_Real},{w,_Real},{k,_Real},{t,_Real},{u,_Real,1},{v,_Real,2}}
*)
MakeVars[vars_, LFvars_] := Module[
	{iLFvars, delete0},
	delete0[0] := Nothing; delete0[x_]/;x>0 := x;
	
	iLFvars = LFvars[[All, 1;;2]];
	
	iLFvars = MapAt[delete0, iLFvars, {All, 2}];
	
	iLFvars = MapAt[Blank, iLFvars, {All,1}];
	
	MapThread[
		Prepend,
		{iLFvars, vars}
	]
]


(*RulesList: {f[x__] -> \[TensorProduct], $D[n_, f][x__] -> \[TensorProduct]*, ...}*)


libraryFunctionsLoad[RulesList_] := Module[
	{compiledFunctions, expressions, wvm, wvmVars},
	
	compiledFunctions = LibraryFunctionLoad@@@(RulesList[[All,2]]);
	compiledFunctions = ExtractLibraryFunction/@compiledFunctions;
	
	expressions = RulesList[[All,1]];
	
	wvmVars = With[{vars =(List@@RulesList[[1,1]])/.q_Pattern :>  q[[1]], LFvars = RulesList[[1, 2, 3]]}, 
		MakeVars[vars, LFvars]
	];
	
	wvm = makeWVM[wvmVars, RulesList[[1, 2, -1]]]; (*The WVM code also has to match the OutType of Library Function*)
	
	compiledFunctions = MapThread[
		MakeCompiledFunction[#1, #2, wvm]&,
		{compiledFunctions, expressions}
	];
	
	Rule@@@(Riffle[expressions, compiledFunctions]//Partition[#,2]&)
]


DerivativeRulesLoad[theory_String] := Module[
	{Pacletdirectory, SymRulesDirec, NRulesDirec, SymRulesDerivatives, NRulesDerivatives, RosettaStone},
	(*THIS WILL BE A BUG IF YOU HAVE MORE THAN ONE VERSION OF THE PACLET*)
	Pacletdirectory = (PacletFind["FelipeBarbosa/SymDALI"]//Last)["Location"];
	
	SymRulesDirec = FileNameJoin[Pacletdirectory,"DerivativeRules" ,theory, "SymRules"];
	NRulesDirec = FileNameJoin[Pacletdirectory,"DerivativeRules", theory, "NRules"];
	
	SymRulesDerivatives = Flatten@(Import[#]&/@FileNames["*.wdx", SymRulesDirec]);
	SymRulesDerivatives = If[ Length@SymRulesDerivatives===1,  SymRulesDerivatives//Last, SymRulesDerivatives];
	
	
	RosettaStone = Import[NRulesDirec <> "/RosettaStone.wdx"];
	NRulesDerivatives = KeyValueMap[
		Rule[#1, libraryFunctionsLoad[#2]]&,
		RosettaStone
	];
	
	{
		SymRulesDerivatives, 
		Association[NRulesDerivatives] 
	}
]


(* ::Section::Closed:: *)
(*Package Footer*)


End[];
EndPackage[];
